import dotenv from "dotenv";
import path from "path";
dotenv.config({ path: path.resolve("./src/config/.env") });

const PORT = process.env.PORT || 80;
const URL_DB = process.env.URL_DB;
const SALT_ROUNDS = process.env.SALT_ROUNDS;
const ENCRYPTION_SECRET_KEY = process.env.ENCRYPTION_SECRET_KEY;
const ACCESS_TOKEN_ADMIN_SECRET = process.env.ACCESS_TOKEN_ADMIN_SECRET;
const REFRESH_TOKEN_ADMIN_SECRET = process.env.REFRESH_TOKEN_ADMIN_SECRET;
const ACCESS_TOKEN_ADMIN_EXPIRES_IN = process.env.ACCESS_TOKEN_ADMIN_EXPIRES_IN;
const ACCESS_TOKEN_USER_SECRET = process.env.ACCESS_TOKEN_USER_SECRET;
const REFRESH_TOKEN_USER_SECRET = process.env.REFRESH_TOKEN_USER_SECRET;
const ACCESS_TOKEN_USER_EXPIRES_IN = process.env.ACCESS_TOKEN_USER_EXPIRES_IN;
const REFRESH_TOKEN_USER_EXPIRES_IN = process.env.REFRESH_TOKEN_USER_EXPIRES_IN;
const REFRESH_TOKEN_ADMIN_EXPIRES_IN = process.env.REFRESH_TOKEN_ADMIN_EXPIRES_IN;

export {
  PORT,
  URL_DB,
  SALT_ROUNDS,
  ENCRYPTION_SECRET_KEY,
  ACCESS_TOKEN_ADMIN_SECRET,
  REFRESH_TOKEN_ADMIN_SECRET,
  ACCESS_TOKEN_ADMIN_EXPIRES_IN,
  ACCESS_TOKEN_USER_SECRET,
  REFRESH_TOKEN_USER_SECRET,
  ACCESS_TOKEN_USER_EXPIRES_IN,
  REFRESH_TOKEN_USER_EXPIRES_IN,
  REFRESH_TOKEN_ADMIN_EXPIRES_IN,
};
